name: ElytraEnchants
version: '${project.version}'
main: com.elytraenchants.ElytraEnchantsPlugin
api-version: '1.16'
description: Allows elytra to be enchanted with chestplate enchantments
authors: [MightyFinger77]

commands:
  elytraenchants:
    description: ElytraEnchants main command
    usage: /elytraenchants <enchant|reload|update>
    permission: elytraenchants.use
    aliases: [ee]

permissions:
  elytraenchants.use:
    description: Allows use of /elytraenchants command
    default: op
  elytraenchants.enchant:
    description: Allows use of /elytraenchants enchant command
    default: op
  elytraenchants.enchant.protection_environmental:
    description: Allows enchanting elytra with Protection
    default: op
  elytraenchants.enchant.protection_fire:
    description: Allows enchanting elytra with Fire Protection
    default: op
  elytraenchants.enchant.protection_explosions:
    description: Allows enchanting elytra with Blast Protection
    default: op
  elytraenchants.enchant.protection_projectile:
    description: Allows enchanting elytra with Projectile Protection
    default: op
  elytraenchants.enchant.thorns:
    description: Allows enchanting elytra with Thorns
    default: op
  elytraenchants.enchant.mending:
    description: Allows enchanting elytra with Mending
    default: op
  elytraenchants.enchant.unbreaking:
    description: Allows enchanting elytra with Unbreaking
    default: op
  elytraenchants.enchant.binding_curse:
    description: Allows enchanting elytra with Binding Curse
    default: op
  elytraenchants.enchant.vanishing_curse:
    description: Allows enchanting elytra with Vanishing Curse
    default: op
  elytraenchants.enchant.*:
    description: Allows enchanting elytra with any allowed enchantment
    default: op
  elytraenchants.reload:
    description: Allows reloading the plugin configuration
    default: op
  elytraenchants.update:
    description: Allows checking for plugin updates
    default: op 